/* Currículo-modelo ilustrativo de 8 períodos. Não substitui PPC/grade de instituição. */
(()=>{
const T=(title,concept,reasoning,application,q,a)=>({id:slug(title),title,concept,reasoning,application,q,a});
const D=(title,ref,topics)=>({id:slug(title),title,ref,topics});
const P=(title,focus,subjects)=>({id:"s"+(window.TO_SEMESTERS.length+1),number:window.TO_SEMESTERS.length+1,title,focus,subjects});
function slug(s){return s.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")}
window.TO_SEMESTERS=[];
const add=(focus,subjects)=>window.TO_SEMESTERS.push(P((window.TO_SEMESTERS.length+1)+"º semestre",focus,subjects));
add("Fundamentos biológicos, sociais e ocupacionais",[
D("Fundamentos de Terapia Ocupacional","otpf",[
T("Ocupação, atividade e participação","Ocupação corresponde às atividades cotidianas significativas que organizam a vida: autocuidado, trabalho, estudo, brincar, lazer e participação social. Não é sinônimo restrito de profissão ou emprego.","A mesma tarefa pode ter sentidos diferentes conforme identidade, contexto, papéis, história de vida e escolha da pessoa. Distinguir atividade executada de participação efetivamente desejada evita avaliar desempenho apenas por velocidade ou independência.","Ao analisar preparo de refeições, investigar o valor cultural da cozinha, barreiras físicas, organização da rotina, suporte disponível e o grau de autonomia definido pela própria pessoa.","Por que atividade e ocupação não são equivalentes?","Uma atividade é uma ação ou conjunto de ações; sua condição de ocupação depende do sentido, papel, contexto e participação atribuídos pela pessoa."),
T("Domínio e processo terapêutico ocupacional","O OTPF-4 organiza o domínio em ocupações, contextos, padrões de desempenho, habilidades de desempenho e fatores do cliente. O processo reúne avaliação, intervenção e resultados.","O raciocínio terapêutico parte das prioridades ocupacionais, identifica facilitadores e barreiras, negocia objetivos relevantes e reavalia resultados no ambiente concreto; diagnósticos isolados não descrevem a participação.","Em avaliação simulada, registrar rotina, ambiente, ocupações valorizadas e obstáculos e então decidir quais informações ainda precisam ser investigadas antes de formular um plano.","Quais são as três etapas gerais do processo no OTPF-4?","Avaliação, intervenção e resultados, conduzidos de modo centrado na pessoa e na participação ocupacional.")]),
D("Anatomia Humana Funcional","cif",[
T("Membro superior e preensão funcional","Cintura escapular, ombro, cotovelo, punho e mão funcionam como cadeia para alcance, estabilização, manipulação e destreza. Preensões de força e de precisão exigem combinações específicas de posicionamento e controle.","A observação precisa considerar amplitude, coordenação, dor, fadiga, sensibilidade, força e compensações durante uma ocupação, evitando atribuir limitação a uma única articulação.","Na ação de abotoar uma camisa, observar pinça, oposição do polegar, estabilização proximal, posição do tronco, características do botão e possibilidades de adaptação.","Por que a estabilização proximal importa para a destreza manual?","Porque controle escapular e do tronco favorece posicionamento eficiente do membro superior e manipulação distal."),
T("Sistema nervoso e controle do movimento","Sistemas motor, sensorial e perceptivo participam de planejamento, iniciação, execução e ajuste dos movimentos. Feedback tátil e proprioceptivo informa força, posição e precisão.","O desempenho depende da integração entre exigência da tarefa, capacidade da pessoa e características do ambiente. Diferenciar dificuldades de planejamento, fraqueza ou processamento sensorial muda a interpretação.","Na transferência entre cadeira e leito, registrar sequência motora, equilíbrio, antecipação postural e pistas ambientais, em vez de observar apenas se a tarefa foi concluída.","Como informação proprioceptiva contribui para a ação?","Fornece informações sobre posição e movimento corporal, necessárias ao ajuste e à coordenação motora.")]),
D("Psicologia do Desenvolvimento","otpf",[
T("Desenvolvimento humano e ciclo de vida","O desenvolvimento combina mudanças biológicas, cognitivas, afetivas e sociais ao longo da vida. Marcos típicos são referências populacionais, não metas rígidas iguais para todos.","A análise ocupacional considera transições, oportunidades de participação, contexto familiar, cultura e desigualdades. Um atraso aparente deve ser investigado com história e ambiente, sem inferência diagnóstica automática.","No brincar de uma criança, examinar iniciativa, interação, brinquedos acessíveis, rotina familiar e experiências disponíveis antes de concluir sobre habilidades individuais.","Por que os marcos não devem ser usados isoladamente?","Porque há variação do desenvolvimento e forte influência de contexto, oportunidade, cultura e condições de saúde."),
T("Vínculos, identidade e papéis","Vínculos afetivos, experiências sociais e papéis de estudante, cuidador, trabalhador ou membro da comunidade participam da construção identitária e das escolhas ocupacionais.","Mudanças de papel podem ampliar possibilidades ou produzir conflito e sobrecarga; é essencial investigar as prioridades e expectativas da própria pessoa, sem impor papéis normativos.","Na transição para a universidade, mapear demandas de estudo, deslocamento, descanso, apoio social e atividades significativas para compreender o equilíbrio cotidiano.","Qual é a relação entre papéis e participação?","Papéis organizam expectativas e rotinas, mas seu sentido e viabilidade dependem das escolhas pessoais e condições do ambiente.")]),
D("Saúde Coletiva e SUS","sus",[
T("Princípios do SUS e cuidado territorial","Universalidade, integralidade e equidade orientam o SUS, articulando atenção, vigilância, promoção e participação social. Território é espaço de relações, recursos, desigualdades e redes de cuidado.","Acesso formal a um serviço não garante participação: transporte, barreiras comunicacionais, disponibilidade de cuidadores e horários podem interferir no cuidado. Projetos devem dialogar com serviços e prioridades locais.","Ao planejar grupo comunitário, levantar acessibilidade do local, demanda da população, articulação com UBS e mecanismos para avaliar participação, não somente presenças.","Como equidade se diferencia de tratar todos igualmente?","Equidade considera desigualdades e necessidades distintas para orientar ofertas que reduzam barreiras reais de acesso e participação."),
T("Determinantes sociais e ocupações","Moradia, renda, raça, gênero, trabalho, escolaridade e políticas públicas influenciam oportunidades de ocupação. Injustiça ocupacional envolve restrições sistemáticas à participação significativa.","Um problema observado como 'falta de adesão' pode refletir jornadas precárias, transporte inadequado ou falta de apoio. A análise ética exige não responsabilizar individualmente pessoas por barreiras sociais.","Para pessoa que trabalha em dois turnos, adaptar propostas à rotina concreta e identificar recursos comunitários viáveis, preservando o poder de escolha.","O que caracteriza uma barreira ocupacional de origem social?","Uma condição estrutural ou contextual que restringe oportunidades de realizar ocupações desejadas.")]),
D("Metodologia Científica I","pesquisa",[
T("Problemas de pesquisa e perguntas investigáveis","Uma pergunta clara delimita população, fenômeno, contexto e resultados de interesse. Em abordagens qualitativas, é útil explicitar experiência e cenário; em quantitativas, variáveis e comparação.","Perguntas extensas, normativas ou com termos indefinidos dificultam seleção de métodos e análise. A viabilidade inclui ética, acesso à literatura, tempo e recursos.","Transformar 'brincar é importante' em 'como crianças com deficiência e suas famílias descrevem barreiras ao brincar em parques públicos da cidade X?' delimita objeto e contexto.","O que torna um problema de pesquisa investigável?","Delimitação conceitual, pertinência, possibilidade de obter evidências e coerência com uma estratégia metodológica."),
T("Leitura crítica e estrutura de artigo","Artigos costumam apresentar introdução, objetivo, métodos, resultados, discussão e limitações. Essa estrutura permite distinguir evidência produzida de interpretação dos autores.","Uma conclusão deve ser avaliada à luz do desenho de estudo, participantes, instrumentos, análise e possíveis vieses. Associação não basta para afirmar causalidade.","Em um estudo de intervenção, verificar comparação, tamanho de amostra, perdas, medidas de desfecho e relevância ocupacional antes de aplicar resultados.","Por que não basta ler o resumo de um artigo?","Porque métodos, medidas, resultados completos e limitações podem alterar a interpretação da conclusão.")])
]);
add("Corpo, movimento, relações e modelos de cuidado",[
D("Neuroanatomia e Neurofisiologia","cif",[
T("Vias motoras e integração sensorial","Sistemas corticoespinais e circuitos subcorticais contribuem para controle motor, enquanto sistemas somatossensoriais oferecem informação para ajuste. Alterações neurológicas podem comprometer ocupações de formas variadas.","Não existe correspondência simples entre lesão e desempenho: plasticidade, demandas ambientais, aprendizagem e estratégias compensatórias modificam a funcionalidade. Avaliar desempenho real é indispensável.","Na atividade de alimentar-se, distinguir problemas de alcance, destreza, sensibilidade, atenção ou organização sequencial e registrar quais adaptações melhoram participação.","Por que topografia de lesão não prediz sozinha a independência?","Porque desempenho ocupacional depende também de contexto, aprendizagem, recursos, prioridades e demandas das tarefas."),
T("Cognição, atenção e funções executivas","Atenção, memória operacional, flexibilidade, planejamento e inibição contribuem para iniciar, sequenciar e concluir tarefas com segurança.","Resultados de testes precisam ser interpretados junto de observação ocupacional e fatores como sono, humor, escolarização, linguagem e características da tarefa.","Ao organizar uma medicação fictícia em caixa semanal, observar compreensão da instrução, sequência e monitoramento de erros; não usar o exercício para recomendar doses.","Que indicador mostra dificuldade executiva em uma tarefa?","Problemas para planejar, alternar etapas, monitorar erros ou ajustar uma estratégia apesar de habilidades motoras suficientes.")]),
D("Cinesiologia e Biomecânica","cif",[
T("Movimento funcional e análise de tarefa","Movimentos articulares e forças biomecânicas interagem com postura, objetos e superfícies durante atividades. Exigências mudam conforme altura, peso, repetição e duração.","Análise de tarefa identifica onde surgem esforço, dor, instabilidade ou fadiga e permite modificar componentes ambientais sem pressupor fortalecimento como única resposta.","No ato de alcançar um armário, avaliar altura, base de suporte, distância do objeto e necessidade de reorganização de materiais de uso frequente.","Como ambiente modifica demanda biomecânica?","Altura, peso, distância, apoio e arranjo espacial alteram amplitude, força e controle postural necessários."),
T("Ergonomia e economia articular","Ergonomia busca compatibilizar demandas da tarefa, pessoa e ambiente. Economia articular envolve reorganizar carga, preensão, repetição, pausas e utensílios conforme objetivos pessoais.","A prescrição de 'postura correta' universal é insuficiente; variação de tarefas, conforto, autonomia, equipamentos e condições concretas de trabalho precisam ser considerados.","Em trabalho artesanal, analisar permanência em pinça, repetição e altura da mesa e testar com a pessoa alternativas de organização e utensílios.","Qual é o foco de uma análise ergonômica centrada na ocupação?","Adequar demandas reais e ambientes à participação segura e significativa, não apenas corrigir uma postura isolada.")]),
D("Modelos e Referenciais da Terapia Ocupacional","otpf",[
T("MOHO: volição, habituação e desempenho","O Modelo da Ocupação Humana organiza compreensão da participação pela interação entre volição (motivação e valores), habituação (hábitos e papéis), capacidade de desempenho e ambiente.","O modelo evita reduzir escolhas a força de vontade, investigando oportunidades, competências percebidas e rotinas. A análise deve demonstrar vínculo entre conceitos e ocupações valorizadas.","Para retorno ao trabalho, explorar interesses, identidade profissional, hábitos interrompidos e apoios possíveis, registrando prioridades negociadas.","Quais quatro componentes interagem no MOHO?","Volição, habituação, capacidade de desempenho e ambiente."),
T("PEO e ajuste pessoa-ambiente-ocupação","O modelo Pessoa-Ambiente-Ocupação analisa desempenho a partir do ajuste dinâmico entre capacidades, condições ambientais e características das ocupações.","Mudanças em qualquer componente podem ampliar participação. Um problema não precisa ser tratado exclusivamente como déficit corporal; adaptação ambiental e modificação da tarefa podem ser efetivas.","Uma estudante com mobilidade reduzida pode participar de laboratório com reorganização de bancada, fluxos acessíveis e materiais ajustados sem mudar seu objetivo acadêmico.","O que significa ajuste no modelo PEO?","Compatibilidade dinâmica entre pessoa, ambiente e ocupação que favorece desempenho e participação.")]),
D("Saúde Mental e Psicopatologia","omsmental",[
T("Sofrimento psíquico e cotidiano","Sofrimento mental pode afetar sono, autocuidado, relações, estudo, trabalho e organização do tempo. A experiência não se resume ao diagnóstico e deve ser compreendida no contexto social.","Observar exclusão, estigma e barreiras de acesso é tão importante quanto levantar dificuldades individuais. Escuta, consentimento, vínculo e articulação com equipe são condições éticas.","Em situação simulada, construir mapa de rotina com atividades desejadas, redes de apoio e mudanças percebidas, evitando rótulos e expectativas padronizadas.","Por que diagnóstico não equivale a perfil ocupacional?","Porque pessoas com o mesmo diagnóstico podem ter diferentes rotinas, recursos, escolhas e barreiras."),
T("Rede de atenção psicossocial e território","A RAPS articula serviços e ações no cuidado em saúde mental no SUS, valorizando base comunitária, continuidade de cuidado e autonomia.","Intervenções ocupacionais precisam dialogar com moradia, trabalho, cultura e vínculos comunitários, respeitando escolhas e evitando práticas segregadoras.","Em oficina comunitária, planejar atividade significativa com participantes, definir como avaliar autonomia e conexões sociais e prever continuidade fora do serviço.","Qual o risco de reduzir oficina terapêutica a passatempo?","Perder objetivos de participação, autonomia, sentido ocupacional e inserção no território.")]),
D("Ética, Direitos Humanos e TO","coffito",[
T("Autonomia, consentimento e confidencialidade","Ética profissional exige respeito à autonomia, privacidade, não discriminação, competência técnica e dever de proteção. Consentimento deve ser informado e proporcional ao contexto.","Registros devem conter o necessário para o cuidado e ser protegidos. Em materiais de ensino e pesquisa, nunca publicar informações identificáveis de usuários sem base ética e autorização adequada.","No relato didático, usar caso totalmente fictício e explicitar objetivos e limites da intervenção, sem copiar imagens ou prontuários reais.","Por que anonimizar apenas o nome pode ser insuficiente?","Porque combinação de datas, locais, imagens e outros detalhes pode permitir reidentificação."),
T("Acessibilidade, capacitismo e participação","Barreiras arquitetônicas, comunicacionais, tecnológicas, atitudinais e institucionais afetam participação. A perspectiva de direitos exige escuta de pessoas com deficiência e remoção de obstáculos.","Adaptação deve ampliar escolhas, não impor solução única. Acessibilidade envolve desenho de processos e relações, além de equipamentos.","Na avaliação de biblioteca, investigar acesso físico, sinalização, formatos de leitura, atitudes da equipe e possibilidade de utilizar os serviços de modo autônomo.","Qual diferença entre acesso físico e participação?","Entrar em um espaço não garante conseguir usar serviços, tomar decisões ou exercer papéis com equidade.")])
]);
add("Avaliação ocupacional e intervenções iniciais",[
D("Avaliação em Terapia Ocupacional","otpf",[
T("Entrevista e perfil ocupacional","O perfil ocupacional reúne história, valores, interesses, papéis, rotinas, experiências e prioridades da pessoa. É construído por escuta e observação, não por checklist isolado.","É preciso separar o que a equipe considera importante do que a pessoa deseja transformar e investigar discrepância entre capacidade em teste e desempenho no cotidiano.","Para cozinhar de forma independente, explorar frequência da atividade, cozinhas disponíveis, utensílios, apoio, riscos percebidos e critérios de sucesso definidos pela pessoa.","O que caracteriza uma boa meta ocupacional?","Ser relevante para a pessoa, observável, contextualizada, negociada e passível de acompanhamento."),
T("Instrumentos, validade e escolha de medidas","Instrumentos padronizados oferecem informação estruturada, mas escolha depende de população, idioma, validade, finalidade, treinamento necessário e condições de aplicação.","Escores não devem ser interpretados fora de manual, contexto cultural ou margem de erro. Registrar condições de avaliação e combinar medidas com evidências do cotidiano.","Antes de usar instrumento de desempenho, verificar versão adaptada, público-alvo e disponibilidade, e decidir como resultados orientarão o plano.","Quais critérios precedem escolha de um instrumento?","Validade, confiabilidade, aplicabilidade, finalidade, população, idioma, treinamento e pertinência ocupacional.")]),
D("Atividades de Vida Diária e Instrumentais","otpf",[
T("AVD: autocuidado e autonomia","Atividades de vida diária abrangem tarefas básicas como alimentação, higiene, vestir e mobilidade funcional. Independência física não equivale automaticamente a autonomia para escolher como receber ajuda.","Avaliar sequência, segurança, fadiga, privacidade e desempenho no ambiente habitual permite estabelecer estratégias que respeitem preferências, cultura e consentimento.","Para banho, analisar transferências, alcance, organização do banheiro, iluminação e apoio escolhido, sem supor que toda pessoa precise executar cada etapa sem assistência.","Como autonomia difere de independência?","Autonomia é decidir sobre a própria vida; independência refere-se ao grau de execução sem assistência."),
T("AIVD: gestão do cotidiano","Atividades instrumentais incluem preparo de refeições, manejo doméstico, finanças, compras, comunicação, transporte e gestão de saúde, conforme classificações utilizadas.","São tarefas com demandas cognitivas, motoras, sociais e ambientais combinadas; avaliá-las apenas em ambiente artificial pode ocultar obstáculos do território.","Na atividade de compras, observar planejamento de lista, orçamento, deslocamento, acessibilidade do estabelecimento e apoios disponíveis.","Por que AIVD requer avaliação contextual?","Porque recursos, transporte, tecnologia, normas sociais e características do domicílio alteram desempenho.")]),
D("Tecnologia Assistiva I","cif",[
T("Tecnologia assistiva e escolha compartilhada","Tecnologia assistiva inclui produtos, recursos, metodologias, estratégias e serviços que ampliam funcionalidade e participação. O recurso adequado depende da tarefa, do ambiente, da pessoa e da manutenção.","Não basta entregar dispositivo: avaliar conforto, treinamento, custo, preferência, disponibilidade e acompanhamento. Abandono pode indicar incompatibilidade, e não 'desinteresse'.","Ao testar engrossador de cabo, comparar realização da tarefa, sensação de esforço, higiene, custo e preferência com e sem adaptação.","O que deve orientar seleção de tecnologia assistiva?","Objetivo ocupacional, contexto de uso, preferência, eficácia, segurança, acesso e possibilidade de acompanhamento."),
T("Adaptações de utensílios e ambiente","Adaptações podem envolver pegadores, estabilizadores, posicionamento de objetos, superfícies antiderrapantes e reorganização da tarefa.","Mudanças precisam ser testadas em condições reais e reavaliadas; soluções caseiras não são automaticamente seguras, sobretudo em tarefas com calor, corte ou transferência.","Para escrita, experimentar diferentes suportes e espessuras, observar conforto, legibilidade e fadiga e registrar resultado preferido.","Quando adaptar tarefa em vez de exigir desempenho sem apoio?","Quando a modificação amplia participação desejada com melhor relação entre esforço, segurança e funcionalidade.")]),
D("Desenvolvimento Infantil e Brincar","otpf",[
T("Brincar como ocupação infantil","Brincar é uma ocupação central na infância e envolve exploração, prazer, imaginação, iniciativa, relações e aprendizagem. A forma de brincar varia culturalmente e ao longo do desenvolvimento.","Uma atividade estruturada pelo adulto não substitui necessariamente brincadeira escolhida pela criança. Observar espontaneidade, oportunidades e barreiras enriquece o raciocínio.","Em parque, observar acesso a brinquedos, interação entre pares, necessidade de apoio e oportunidades de escolha para criança com mobilidade limitada.","Por que avaliar participação no brincar, e não só habilidades isoladas?","Porque o brincar tem dimensão de escolha, significado, contexto social e acesso a oportunidades."),
T("Rotinas familiares e participação escolar inicial","Sono, alimentação, higiene, deslocamentos e relações entre família e escola estruturam a participação infantil. Expectativas precisam ser negociadas com criança, cuidadores e educadores.","Condições de tempo, recursos, valores culturais e ambiente físico podem facilitar ou restringir rotinas. Evitar culpar a família por limitações de acesso.","Mapear entrada na escola, momentos de brincar, refeições, transições e comunicação, identificando barreiras com equipe escolar e cuidadores.","Por que rotina familiar importa na avaliação infantil?","Porque revela oportunidades e obstáculos concretos para as ocupações da criança nos ambientes em que vive.")]),
D("Pesquisa Quantitativa e Bioestatística","pesquisa",[
T("Variáveis e medidas de resultados","Variáveis devem possuir definições operacionais claras. Em Terapia Ocupacional, medidas podem explorar frequência de participação, satisfação, desempenho ou uso de recursos, conforme instrumentos válidos.","Diferença estatística não implica necessariamente mudança clinicamente ou ocupacionalmente relevante. Considerar efeito, intervalo de confiança e qualidade da medida.","Ao avaliar programa de treino de AVD, diferenciar melhora numérica em escore de mudança percebida na rotina cotidiana.","O que é definição operacional?","Descrição de como um conceito será efetivamente observado ou medido na pesquisa."),
T("Amostragem, viés e interpretação","Amostras por conveniência, perdas de seguimento e fatores de confusão podem limitar generalização. Estudos observacionais não demonstram causalidade por si.","Descrever critérios de inclusão, contexto e fatores que podem afetar os resultados ajuda a reconhecer alcance das conclusões.","Em levantamento de satisfação, verificar quem respondeu, quem ficou de fora e se houve barreiras de acesso ao formulário.","Por que viés de seleção é relevante?","Porque participantes podem diferir sistematicamente dos não incluídos e distorcer resultados.")])
]);
add("Ciclos de vida e contextos de intervenção",[
D("Terapia Ocupacional em Pediatria","otpf",[
T("Participação infantil em casa e na escola","O cuidado pediátrico orientado à ocupação integra interesses da criança, participação familiar, brincadeira, autocuidado e demandas escolares.","É essencial analisar pessoa, atividade e ambiente, construindo estratégias com criança, responsáveis e equipe educacional, em vez de propor treino descontextualizado.","Em sala de aula, considerar cadeira, materiais, tempo para escrita, recreio e forma de demonstrar aprendizagem para ampliar participação.","Qual é a unidade central de análise em TO pediátrica?","A participação da criança em ocupações significativas e nos ambientes reais."),
T("Processamento sensorial e participação","Modulação, discriminação sensorial e respostas aos estímulos podem influenciar conforto e engajamento. Hipóteses precisam ser formuladas com cautela e avaliação adequada.","Evitar presumir que comportamento decorra exclusivamente de uma causa sensorial; considerar comunicação, ambiente, demandas, emoções e necessidades da criança.","Diante de desconforto em refeitório, investigar ruído, iluminação, cheiro, rotina, previsibilidade e opções de adaptação colaborativa.","Por que não rotular toda dificuldade escolar como sensorial?","Porque participação resulta de múltiplos fatores; avaliação deve examinar hipóteses concorrentes e contexto.")]),
D("Terapia Ocupacional em Saúde Mental","omsmental",[
T("Projetos de vida e cotidiano em saúde mental","Intervenções podem ampliar participação em autocuidado, vínculos, trabalho, estudo e lazer, reconhecendo desejos, recursos e dificuldades concretas.","Cuidado orientado à recuperação não equivale a exigir produtividade ou normalização de rotinas; prioriza autonomia, direitos, pertencimento e escolhas.","Em grupo, construir com participantes possibilidades de circulação no território e atividades de interesse, verificando acessibilidade e redes de apoio.","O que distingue uma intervenção centrada em recuperação?","A valorização de projetos próprios, autonomia, direitos e participação, e não apenas redução de sintomas."),
T("Grupos terapêuticos e análise de atividades","Grupos devem ter propósito, critérios de participação, estrutura flexível e meios de avaliar resultados ocupacionais e relacionais.","O uso de artes, culinária ou jogos não torna uma ação automaticamente terapêutica; significado, mediação, vínculos e objetivos precisam estar explícitos.","Em oficina de produção cultural, planejar escolhas coletivas, papéis assumidos, acessibilidade e oportunidade de circulação das produções.","Quando uma oficina deixa de ser mero passatempo?","Quando há intencionalidade, análise, participação escolhida e acompanhamento de objetivos relevantes.")]),
D("Reabilitação Física I","cif",[
T("Participação após alterações musculoesqueléticas","Dor, restrição de movimento, fraqueza e alterações de sensibilidade podem afetar AVD, trabalho e lazer. A análise deve considerar tarefas concretas e tempo de recuperação.","Prescrição de condutas exige avaliação e supervisão adequadas. É importante identificar segurança, progressão de exigências, estratégias compensatórias e contexto ambiental.","Após lesão de punho fictícia, analisar abertura de embalagens, higiene e preparo de alimentos e explorar alternativas conforme orientações de equipe responsável.","Como definir prioridade na reabilitação física?","Pelas ocupações escolhidas, necessidades de segurança e barreiras reais, não somente pela amplitude de movimento."),
T("Fadiga, energia e rotina","Fadiga pode interferir na participação mesmo quando força está preservada. Planejamento envolve priorização, alternância de atividades, pausas e adaptação de demandas.","A pessoa deve ser parceira das escolhas; repouso excessivo ou metas genéricas podem limitar participação. Monitorar impacto em tarefas significativas e ajustar estratégias.","Em rotina universitária com fadiga, comparar horários de maior energia e distribuir deslocamentos, atividades acadêmicas e descanso.","Que informação é essencial em avaliação da fadiga?","Como ela se manifesta em ocupações específicas, em quais condições e quais ajustes funcionam para a pessoa.")]),
D("Terapia Ocupacional Social e Comunitária","sus",[
T("Território, vulnerabilidade e direitos","A Terapia Ocupacional social analisa participação, cotidiano e acesso a direitos diante de desigualdades, redes de proteção e conflitos sociais.","Projetos coletivos precisam evitar individualizar problemas estruturais; escuta, articulação intersetorial e pactuação com comunidades são centrais.","Em projeto com jovens, mapear espaços culturais, mobilidade, oportunidades de formação e participação política, valorizando escolhas e protagonismo.","Por que território vai além de localização geográfica?","Porque inclui relações, recursos, conflitos, instituições e oportunidades efetivas de participação."),
T("Trabalho coletivo e participação social","Ações comunitárias articulam sujeitos, serviços e políticas para construir possibilidades de participação em atividades significativas.","Indicadores incluem vínculos, acesso, autonomia e mudanças no ambiente; contar oficinas realizadas não basta para avaliar resultado.","Num centro comunitário, criar rodas de mapeamento de recursos, pactuar iniciativas e acompanhar quem consegue manter participação.","Como avaliar uma ação coletiva com foco ocupacional?","Observando mudanças de acesso, vínculos, autonomia, continuidade e participação valorizadas pelos envolvidos.")]),
D("Tecnologia Assistiva II e Acessibilidade","cif",[
T("Acessibilidade arquitetônica e ambiental","Rotas, portas, mobiliário, sanitários, transporte e sinalização interferem no uso de espaços. Normas técnicas podem orientar soluções, mas avaliação depende também das tarefas reais.","Acessibilidade não se reduz à presença de rampa; é preciso examinar deslocamento completo, comunicação, mobiliário, alternativas e autonomia de uso.","Em visita didática à biblioteca, registrar percurso da rua até acervo e mesas, identificando barreiras e propondo melhorias compatíveis com uso cotidiano.","Por que a existência de rampa não garante acessibilidade?","Porque participação exige continuidade da rota, acesso a serviços, comunicação e uso efetivo do ambiente."),
T("Desenho universal e participação","Desenho universal propõe ambientes e produtos utilizáveis pelo maior número possível de pessoas, sem excluir necessidade de adaptações individuais.","Decisões devem considerar diversidade de corpos, idades e formas de comunicação. Testes com usuários ajudam a identificar limites de soluções presumidas.","Ao reorganizar sala de estudos, combinar circulação ampla, alturas variadas, contraste e opções de uso para diferentes necessidades.","Desenho universal elimina adaptações individuais?","Não; amplia acessibilidade geral, mas necessidades específicas podem exigir recursos complementares.")])
]);
add("Intervenção avançada e contextos especializados",[
D("Terapia Ocupacional em Neurologia","cif",[
T("AVC e desempenho ocupacional","Alterações motoras, sensitivas, cognitivas, perceptivas e comunicacionais após AVC podem afetar autocuidado e papéis sociais.","Intervenção centrada em ocupações demanda avaliação de capacidades e barreiras, metas negociadas e colaboração com equipe. Evitar associar recuperação exclusivamente a uma técnica.","Para retornar à alimentação, observar preensão, coordenação, postura, percepção e características do ambiente, testando estratégias sob supervisão.","Por que o treino isolado de movimento é insuficiente?","Porque melhoria de componente não garante transferência para ocupação contextualizada."),
T("Apraxias, negligência e cognição funcional","Apraxias envolvem dificuldades de realizar ações aprendidas não explicadas somente por força; negligência espacial pode afetar atenção e exploração de parte do ambiente.","É fundamental diferenciar problemas de compreensão, visão, sensibilidade, planejamento e atenção por avaliação interdisciplinar.","No preparo simulado de sanduíche, observar sequência, busca de utensílios e erros em diferentes posições para formular hipóteses.","Qual risco de avaliar negligência apenas por força muscular?","Ignorar componente atencional-perceptivo que restringe o uso do espaço e a segurança em tarefas.")]),
D("Terapia Ocupacional em Gerontologia","otpf",[
T("Envelhecimento, papéis e participação","Envelhecimento é heterogêneo. A avaliação considera história ocupacional, redes sociais, barreiras ambientais, saúde e oportunidades de escolha.","Evitar equiparar idade a incapacidade ou infantilizar a pessoa. Identificar riscos sem retirar autonomia e respeitar prioridades.","Para pessoa idosa que deseja seguir cultivando jardim, avaliar acesso ao quintal, ferramentas, equilíbrio, rotina e preferências para manter a ocupação.","O que combate o idadismo na prática?","Escuta da pessoa, individualização, respeito à autonomia e recusa de estereótipos baseados em idade."),
T("Cognição, rotina e participação no envelhecimento","Alterações cognitivas podem impactar organização do cotidiano, mas o desempenho varia com suporte ambiental, hábitos e complexidade da tarefa.","É importante observar desempenho funcional e combinar orientações com rede de apoio, consentimento e segurança, evitando inferência diagnóstica por observações pontuais.","Em rotina de compras, avaliar listas, pistas visuais, transporte, familiaridade do percurso e divisão de etapas.","Como adaptar tarefa sem anular autonomia?","Oferecendo apoios proporcionais, escolhas e estratégias ambientais pactuadas.")]),
D("Ergonomia e Terapia Ocupacional no Trabalho","cif",[
T("Análise ergonômica da atividade real","Trabalho real envolve variabilidade, restrições, metas, relações e improvisações que não aparecem inteiramente na descrição formal do cargo.","Analisar posturas sem demandas organizacionais, pausas e metas de produção pode responsabilizar trabalhador por condições inadequadas.","Em atividade de embalagem, mapear ciclo de trabalho, ritmo, mudanças de tarefa, tempo de recuperação, ferramentas e oportunidades de decisão.","Qual diferença entre tarefa prescrita e atividade real?","Tarefa prescrita é o esperado formalmente; atividade real inclui ajustes feitos diante de condições concretas."),
T("Retorno ao trabalho e adaptações","Retorno sustentável ao trabalho depende de demandas essenciais do cargo, condições de saúde, suporte organizacional e negociação de ajustes.","Adaptações podem envolver jornada, layout, redistribuição de atividades ou tecnologia assistiva; requerem diálogo e cuidado com confidencialidade.","Em caso fictício, negociar metas graduais, pausas e acesso a equipamentos, sem divulgar detalhes clínicos desnecessários ao empregador.","Qual é o objetivo central de um plano de retorno?","Favorecer participação laboral segura, viável e sustentável respeitando direitos e contextos.")]),
D("Terapia Ocupacional em Contexto Hospitalar","otpf",[
T("Ocupações no ambiente hospitalar","Hospitalização modifica rotina, papéis, privacidade, sono, autocuidado e decisões. A intervenção deve reconhecer prioridades e condições clínicas.","Planejamento depende de coordenação com equipe e avaliação de segurança. Preservar participação pode envolver pequenas escolhas significativas em ambiente limitado.","Em internação simulada, identificar possibilidades autorizadas de higiene, comunicação com familiares e atividades de interesse, respeitando restrições clínicas.","Por que o cotidiano importa durante hospitalização?","Porque manter escolhas e papéis ocupacionais pode apoiar participação e bem-estar mesmo em ambiente restritivo."),
T("Planejamento da alta e continuidade de cuidado","Alta envolve transição entre hospital, domicílio e serviços; exige antecipar demandas, ambientes, cuidadores, recursos e rede assistencial.","Não confundir aptidão para receber alta com autonomia em todas as tarefas. Registrar necessidades, instruções e articulação interprofissional de forma individualizada.","Para retorno a domicílio, avaliar previamente barreiras de banheiro, escadas, rotinas e disponibilidade de apoio, articulando encaminhamentos adequados.","Qual é a finalidade do planejamento da alta?","Organizar transição segura e continuidade de participação e cuidado no ambiente de vida.")]),
D("Recursos Terapêuticos e Análise de Atividade","otpf",[
T("Análise graduada de uma atividade","Analisar uma atividade implica investigar materiais, sequência, tempo, movimentos, cognição, sensações, interações e significado.","Graduar exigências envolve modificar quantidade de etapas, apoio, ferramentas ou ambiente; deve preservar a ocupação desejada e verificar resposta da pessoa.","Em atividade de jardinagem, ajustar peso de recipientes, altura da bancada e duração, observando participação, fadiga e satisfação.","O que significa graduar atividade?","Ajustar exigências e apoios para adequar desafio, participação e objetivo terapêutico."),
T("Expressão, criatividade e significado ocupacional","Atividades expressivas podem favorecer identidade, comunicação, vínculos e participação, desde que objetivos sejam negociados e a escolha seja respeitada.","Atribuir significados psicológicos fixos a uma produção artística sem evidência e diálogo é inadequado. Importa a experiência relatada pela pessoa.","Em grupo de colagem, perguntar sobre sentidos atribuídos à atividade e registrar preferências, escolhas e interação, sem interpretar imagens arbitrariamente.","Por que produção expressiva não deve ser interpretada isoladamente?","Porque seu significado é pessoal, contextual e precisa de diálogo com quem produziu.")])
]);
add("Evidências, gestão e prática supervisionada",[
D("Prática Baseada em Evidências","pesquisa",[
T("Integração de evidência e preferência","Prática baseada em evidências articula melhor pesquisa disponível, expertise profissional, contexto e valores da pessoa.","Um resultado estatisticamente favorável pode não se aplicar ao público, recurso ou objetivo em questão. A decisão requer análise crítica e comunicação transparente.","Na escolha de estratégia para AVD, relacionar força da evidência, disponibilidade local, metas e preferência do participante.","Quais elementos compõem decisão baseada em evidências?","Pesquisa relevante, julgamento profissional, contexto e preferências da pessoa."),
T("Hierarquias e qualidade metodológica","Desenhos experimentais, observacionais e qualitativos respondem a perguntas distintas. Hierarquias de evidências não substituem avaliação do método e adequação à pergunta.","Para compreender experiência vivida, estudo qualitativo pode ser mais apropriado do que ensaio clínico; para efeitos causais, desenho com comparador pode ser necessário.","Ao revisar estudo de participação, relacionar pergunta, desenho, amostragem, instrumentos, vieses e validade das inferências.","Por que 'maior nível de evidência' não basta?","Porque adequação ao fenômeno e qualidade de execução determinam utilidade e interpretação.")]),
D("Terapia Ocupacional e Inclusão Escolar","otpf",[
T("Participação no currículo e ambiente escolar","Inclusão escolar exige acesso ao currículo, interações, brincadeiras, comunicação e participação nas atividades da escola.","Propostas devem ser construídas com estudante, professores, família e equipe, evitando retirada desnecessária da convivência e redução da intervenção a treinos individuais.","Ao estudar barreiras à escrita, considerar atividades alternativas de demonstração de conhecimento, apoio tecnológico e organização da sala.","Por que inclusão vai além de estar matriculado?","Porque participação implica aprender, interagir, escolher e utilizar plenamente oportunidades escolares."),
T("Adaptação pedagógica e tecnologias de apoio","Recursos de escrita, comunicação alternativa, organização visual e materiais acessíveis podem remover obstáculos, conforme avaliação e articulação educacional.","Adaptações devem favorecer a autoria do estudante e não transformar a atividade em mera execução assistida. Acompanhar aceitação e efetividade.","Para apresentar trabalho, combinar diferentes formatos de expressão e avaliar participação com critérios de aprendizagem acordados.","Qual deve ser o resultado central de uma adaptação escolar?","Mais acesso e participação significativa na atividade educacional escolhida.")]),
D("Órteses, Próteses e Mobilidade","cif",[
T("Princípios de indicação e acompanhamento de órteses","Órteses podem apoiar posicionamento ou função conforme indicação profissional, objetivos ocupacionais e condições individuais.","Seleção, confecção e ajustes exigem competências específicas, avaliação de pele, conforto e seguimento; material didático não substitui prescrição ou supervisão.","Em situação simulada, discutir metas de uso durante atividades, aceitação, barreiras de higiene e necessidade de reavaliação pela equipe.","Por que uso de órtese precisa de acompanhamento?","Porque adaptação, conforto, integridade da pele e objetivos funcionais podem mudar."),
T("Mobilidade e participação nos ambientes","Recursos de mobilidade influenciam deslocamentos, transporte, estudo e participação comunitária. Adequação depende de acessibilidade, postura, transferências e escolhas da pessoa.","Não avaliar equipamento isolado de suas condições de uso: trajetos, manutenção, armazenamento e transporte alteram viabilidade.","No trajeto casa-faculdade, investigar transporte, calçadas, entradas, elevadores e permanência em aula antes de escolher prioridades de adaptação.","Por que avaliação comunitária é necessária?","Porque um recurso útil em ambiente controlado pode ser inviável em trajetos e serviços reais.")]),
D("Gestão de Serviços e Projetos em TO","sus",[
T("Planejamento de serviço orientado a necessidades","Planejamento envolve conhecer demanda, rede, recursos, prioridades, capacidade de atendimento e objetivos mensuráveis de participação.","Eficiência não deve ser confundida com número de atendimentos; indicadores precisam considerar acesso, continuidade, experiência do usuário e resultados.","Para projeto em UBS, definir demanda territorial, equipe, fluxo de encaminhamento, critérios de acesso e monitoramento de participação.","Por que contar atendimentos não basta?","Porque volume de procedimentos não descreve qualidade, equidade nem resultados relevantes."),
T("Indicadores e avaliação de projetos","Indicadores devem ter definição, fonte de dados, periodicidade e vínculo com objetivo. Combinar dados quantitativos e relatos de participantes enriquece avaliação.","Evitar indicadores que incentivem exclusão de casos complexos ou produção de números sem sentido. Transparência e ética orientam uso de dados.","Em oficina comunitária, combinar frequência com satisfação, acesso a espaços e continuidade de ocupações escolhidas.","Como identificar um indicador útil?","Ele mede algo pertinente ao objetivo, pode ser obtido de modo ético e subsidia decisões de melhoria.")]),
D("Estágio Supervisionado I","wfot",[
T("Observação e raciocínio de campo","No campo supervisionado, relacionar contexto institucional, demandas, ocupações, avaliação e decisões da equipe sem ultrapassar atribuições do estudante.","Registro reflexivo diferencia descrição de fatos, hipóteses e decisões supervisionadas. Privacidade deve ser preservada integralmente.","Em diário fictício, anotar atividade observada, barreiras ambientais, questões para discussão e aprendizagens sem qualquer dado identificável.","O que um diário reflexivo deve distinguir?","Observação objetiva, interpretação provisória e aprendizado elaborado com supervisão."),
T("Plano de aprendizagem e supervisão","Objetivos de estágio podem incluir comunicação, análise de tarefa, registro, ética e colaboração interprofissional, pactuados com supervisores.","Feedback concreto identifica competências demonstradas, lacunas e ações de melhoria. Estudante não deve executar procedimentos além de sua habilitação ou supervisão.","Criar plano semanal com observação de avaliação, discussão de caso simulado, feedback e autoavaliação documentada.","Por que supervisionar é essencial?","Porque protege usuários e estudantes e permite desenvolver competências com orientação e responsabilidade.")])
]);
add("Intervenções complexas, pesquisa e TCC",[
D("Terapia Ocupacional em Cuidados Paliativos","otpf",[
T("Ocupações significativas e qualidade de vida","Cuidados paliativos consideram sofrimento multidimensional e prioridades da pessoa e de sua rede, incluindo papéis, conforto, vínculos e atividades de sentido.","A intervenção não deve impor produtividade ou independência como metas universais. Prioridades podem mudar e precisam de revisão contínua e colaboração com equipe.","Em caso fictício, negociar a possibilidade de ouvir música com familiar, escrever mensagem ou participar de ritual valorizado, respeitando energia e preferências.","Qual critério define uma meta ocupacional em cuidados paliativos?","O significado e a viabilidade para a pessoa naquele momento, com respeito ao conforto e às escolhas."),
T("Comunicação e suporte a cuidadores","Cuidadores vivenciam demandas ocupacionais próprias. Comunicação sobre tarefas, suportes e redes deve respeitar papéis, autonomia e condições emocionais.","Cuidar não significa transformar família em equipe clínica sem escolha, apoio ou treinamento; identificar sobrecarga e possibilidades de cuidado compartilhado.","Em planejamento de alta simulado, mapear quem deseja e pode oferecer apoio e quais recursos e encaminhamentos são necessários.","Por que avaliar rotina do cuidador?","Porque apoio sustentável depende de tempo, recursos, consentimento, relações e necessidades da própria pessoa cuidadora.")]),
D("Reabilitação Cognitiva e Comunitária","cif",[
T("Cognição aplicada às ocupações","Intervenções cognitivas ocupacionais focam planejamento, memória, atenção e monitoramento em tarefas significativas, com apoios ambientais quando pertinentes.","Melhoria em exercício descontextualizado não demonstra transferência automática; acompanhamento deve observar participação real e estratégias utilizadas.","Na organização de agenda acadêmica, testar lembretes, divisão de tarefas e revisão de prazos, observando adoção e autonomia.","Como verificar transferência de treino cognitivo?","Observando mudanças em ocupações reais e nas estratégias usadas em contextos relevantes."),
T("Participação social e reinserção comunitária","Comunidade envolve transporte, lazer, espaços públicos, redes sociais e exercício de papéis. Barreiras físicas e atitudinais podem restringir escolhas.","Planejamento intersetorial, exposição graduada quando indicada e soluções de acesso devem partir das prioridades da pessoa, nunca da ideia de normalização social.","Para retomada de biblioteca comunitária, mapear deslocamento, horários, acessibilidade e acompanhante escolhido.","Por que participação comunitária deve integrar o plano?","Porque qualidade de vida e ocupações acontecem além do serviço de saúde.")]),
D("Pesquisa Qualitativa Aplicada","pesquisa",[
T("Entrevistas, observação e reflexividade","Pesquisa qualitativa investiga experiências, sentidos e processos em contexto. Entrevistas e observações exigem roteiro coerente, consentimento e sensibilidade à relação pesquisador-participante.","Reflexividade envolve reconhecer pressupostos e posição do pesquisador, registrando decisões analíticas. Citações de participantes devem preservar confidencialidade.","Na análise de vivências de estudantes com deficiência, desenvolver perguntas abertas, registrar contexto e revisar influência das expectativas do entrevistador.","Por que reflexividade não é opcional?","Porque posicionamento e decisões do pesquisador influenciam coleta, análise e interpretação."),
T("Análise temática e credibilidade","Análise temática envolve familiarização, codificação, construção e revisão de temas fundamentados em dados, mantendo trilha analítica.","Um tema não é apenas título frequente: precisa representar padrão interpretativo coerente e sustentado por trechos relevantes, sem ocultar contradições.","Em depoimentos fictícios sobre mobilidade, diferenciar códigos sobre transporte, autonomia e participação e explicar como emergem temas.","Como demonstrar qualidade em análise temática?","Por transparência de método, coerência entre dados e interpretação, reflexividade e descrição de decisões.")]),
D("Projeto de TCC e Revisão de Literatura","pesquisa",[
T("Delimitação de tema e justificativa","Um TCC viável articula problema relevante, população, fenômeno ocupacional, contexto e pergunta clara, com justificativa apoiada em literatura verificável.","É necessário distinguir lacuna científica de ausência de busca. Viabilidade, acesso a dados, tempo e exigência ética devem ser examinados antes de definir método.","Propor estudo sobre acessibilidade do brincar em praças de um município, definindo sujeitos, contexto, perguntas e limites de coleta.","Qual erro frequente na justificativa de TCC?","Apresentar opinião de relevância sem diálogo com evidências e lacuna delimitada."),
T("Métodos, ética e cronograma","Métodos descrevem desenho, cenário, participantes ou fontes, critérios, coleta, análise e aspectos éticos. Cronograma deve refletir etapas e riscos reais.","Pesquisas com seres humanos exigem avaliação ética conforme regras aplicáveis e orientação institucional; não se presume dispensa por serem atividades acadêmicas.","Construir calendário com projeto, busca piloto, revisão, submissão ética se aplicável, coleta apenas após autorizações, análise e escrita.","Que elementos tornam um método reprodutível?","Critérios explícitos, procedimentos descritos, instrumentos, tratamento dos dados e lógica de análise.")]),
D("Estágio Supervisionado II","wfot",[
T("Planejamento compartilhado de intervenção","No estágio avançado, estudante sob supervisão integra avaliação, escolha de ocupações prioritárias, objetivos, plano e acompanhamento de resultados.","Decisões devem ser justificadas por evidências e contexto, com registro de revisões e comunicação ética à equipe. Não ultrapassar competências ou normas locais.","Em discussão de caso inteiramente fictício, comparar objetivos de autocuidado, ambiente e suporte e propor indicadores de acompanhamento.","Qual é a base do planejamento compartilhado?","Prioridades ocupacionais da pessoa, avaliação contextual, evidências e supervisão."),
T("Avaliação de resultados e reflexão profissional","Desfechos podem incluir participação, satisfação, desempenho, autonomia e mudanças ambientais, medidos de forma adequada à meta.","Reconhecer limites do estágio e registrar incertezas permite aprendizagem responsável. Uma intervenção não é 'bem-sucedida' apenas porque foi executada.","No encerramento de caso simulado, comparar objetivos iniciais e resultados, registrar barreiras persistentes e recomendações de continuidade.","Por que revisar metas ao final do acompanhamento?","Para verificar relevância, progresso, limites e necessidade de continuidade do cuidado.")])
]);
add("Síntese profissional, TCC e transição para carreira",[
D("Seminários Integradores em TO","otpf",[
T("Raciocínio ocupacional em casos complexos","Casos complexos combinam condições clínicas, contextos sociais, decisões éticas e prioridades que podem entrar em tensão.","A formulação deve explicitar hipóteses, dados faltantes, preferências, riscos e colaboração com equipe; evitar respostas automáticas baseadas em diagnóstico.","Em caso didático com barreiras de transporte e AVD, elaborar mapa de problemas ocupacionais, fatores ambientais e opções discutidas com a pessoa.","O que torna raciocínio clínico transparente?","Explicitar dados, hipóteses, limites, alternativas e critérios de decisão."),
T("Integração de modelos e evidências","Modelos teóricos ajudam a formular problemas, mas devem ser usados coerentemente com objetivos, contexto e evidências disponíveis.","Misturar conceitos sem justificativa pode obscurecer análise. Recomenda-se indicar qual referencial responde a cada aspecto do problema e seus limites.","Comparar MOHO e PEO em retorno à universidade: o primeiro enfatiza volição e habituação; o segundo, ajuste entre pessoa, ambiente e ocupação.","Quando comparar modelos é útil?","Quando esclarece hipóteses diferentes e orienta escolhas de avaliação e intervenção.")]),
D("Políticas Públicas e Defesa de Direitos","sus",[
T("Cuidado intersetorial e redes de proteção","Participação ocupacional depende de saúde, educação, assistência social, trabalho, cultura e mobilidade, exigindo articulação de políticas e serviços.","Encaminhamento sem conexão entre serviços pode produzir fragmentação. Planejar fluxos e comunicação com consentimento favorece continuidade.","Para jovem em transição escolar, mapear serviços educacionais, oportunidades de formação, transporte e rede de proteção.","O que significa atuação intersetorial?","Coordenação entre diferentes áreas e políticas diante de necessidades que ultrapassam um setor."),
T("Advocacy, cidadania e participação","Defesa de direitos em Terapia Ocupacional envolve reconhecer barreiras estruturais e apoiar protagonismo de pessoas e coletivos.","Não substituir a voz do sujeito pelo olhar técnico; decisões devem incorporar participação social e conhecimento da comunidade.","Em projeto de acessibilidade cultural, organizar escuta de usuários e pactuar prioridades com gestores e organizações locais.","Qual cuidado ético é central na defesa de direitos?","Fortalecer protagonismo e decisões das pessoas envolvidas, sem falar por elas indevidamente.")]),
D("TCC: Escrita Científica e Defesa","pesquisa",[
T("Discussão de resultados e limites","Discussão relaciona achados à pergunta, literatura e contexto sem extrapolar método. Limitações precisam considerar desenho, seleção, instrumentos e possíveis vieses.","Resultados inesperados merecem análise, não ocultamento. Citação precisa corresponder a fonte realmente consultada, sem bibliografia inventada.","Ao observar baixa participação em programa, discutir barreiras de acesso e alcance da amostra, não afirmar falta de motivação sem evidência.","Como evitar extrapolação na discussão?","Manter conclusões proporcionais ao método, dados, incertezas e contexto."),
T("Apresentação oral e argumentação","Defesa exige narrativa clara: problema, justificativa, objetivos, método, resultados, limites e implicações ocupacionais.","Slides devem privilegiar hierarquia visual e dados interpretáveis; perguntas da banca são oportunidades de esclarecer escolhas, inclusive incertezas.","Treinar apresentação de projeto com tempo, gráficos legíveis e resposta fundamentada a perguntas sobre amostragem e ética.","O que torna uma defesa convincente?","Coerência entre pergunta, método, evidências, interpretação e reconhecimento de limites.")]),
D("Gestão de Carreira e Educação Continuada","wfot",[
T("Áreas de atuação e desenvolvimento profissional","Trajetórias podem incluir saúde, assistência social, educação, trabalho, cultura, gestão, pesquisa e docência, respeitando regulamentações profissionais.","Planejamento de carreira considera interesses, competências, supervisão, formação continuada, ética e oportunidades locais, sem prometer habilitação automática.","Construir mapa de competências e portfólio com experiências supervisionadas, projetos acadêmicos e plano de aprendizado.","Por que portfólio não deve expor prontuários?","Porque confidencialidade e proteção de dados continuam valendo em materiais de apresentação profissional."),
T("Leitura de evidências e atualização","Competência profissional exige reconhecer mudanças de diretrizes, literatura e normas. Atualização envolve avaliar qualidade e relevância das fontes.","Cursos e certificados isolados não substituem capacidade de raciocínio crítico nem autorizações legais específicas.","Planejar revisão trimestral de publicações institucionais e registrar mudanças com referência, data e repercussão na prática.","Qual é sinal de atualização responsável?","Conferir fontes primárias, avaliar qualidade, registrar datas e adaptar decisões ao contexto e escopo profissional.")]),
D("Ética e Documentação Profissional","coffito",[
T("Registros ocupacionais e proteção de dados","Documentação útil descreve objetivos, observações pertinentes, decisões, evolução e encaminhamentos com linguagem clara e respeito à privacidade.","Adjetivos vagos, julgamentos morais e dados excessivos comprometem qualidade. Usar sistemas autorizados e normas da instituição.","Em registro simulado, descrever desempenho na tarefa observada e barreiras contextuais, separando fato de hipótese profissional.","Como distinguir um registro de qualidade?","Ele é factual, pertinente, claro, proporcional e protege informações pessoais."),
T("Responsabilidade, limites e colaboração","A atuação deve respeitar normas profissionais, consentimento, atribuições, competências, documentação e articulação interprofissional.","Em situações de incerteza, buscar supervisão e consulta à regulamentação aplicável é parte da responsabilidade técnica.","Ao receber demanda fora da competência do estudante, registrar a questão e encaminhá-la ao supervisor, sem executar procedimento por conta própria.","Qual deve ser a conduta diante de limite de competência?","Reconhecer o limite, buscar supervisão e encaminhar de forma responsável.")])
]);
window.TO_ALL=window.TO_SEMESTERS.flatMap(semester=>semester.subjects.flatMap(discipline=>discipline.topics.map(topic=>({...topic,semester:semester.number,semesterId:semester.id,discipline:discipline.title,disciplineId:discipline.id,ref:discipline.ref}))));
window.TO_COUNTS={semesters:window.TO_SEMESTERS.length,disciplines:window.TO_SEMESTERS.reduce((n,s)=>n+s.subjects.length,0),topics:window.TO_ALL.length};
})();